CREATE TABLE IF NOT EXISTS NOTEBOOK(
  ID BIGSERIAL PRIMARY KEY,
  NOTEBOOKNAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTEBOOKENTRY(
  ID BIGSERIAL PRIMARY KEY,
  ENTRYTEXT CLOB(90000),
  NOTEBOOKID BIGSERIAL
);

ALTER TABLE NOTEBOOKENTRY ADD FOREIGN KEY (NOTEBOOKID) REFERENCES NOTEBOOK(ID);

/*Schema for MYSQL
CREATE TABLE NOTEBOOK(ID BIGSERIAL PRIMARY KEY,NOTEBOOKNAME VARCHAR(50) NOT NULL);
CREATE TABLE NOTEBOOKENTRY(ID INT PRIMARY KEY,ENTRYTEXT LONGTEXT,  NOTEBOOKID INT);
ALTER TABLE NOTEBOOKENTRY ADD FOREIGN KEY (NOTEBOOKID) REFERENCES NOTEBOOK(ID);
*/